// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SustavZaPreporukuMobitelaML.Model
{
    public class ModelInput
    {
        [ColumnName("brand"), LoadColumn(0)]
        public string Brand { get; set; }


        [ColumnName("model"), LoadColumn(1)]
        public string Model { get; set; }


        [ColumnName("four_g_network"), LoadColumn(2)]
        public float Four_g_network { get; set; }


        [ColumnName("EDGE"), LoadColumn(3)]
        public float EDGE { get; set; }


        [ColumnName("announced"), LoadColumn(4)]
        public float Announced { get; set; }


        [ColumnName("weight_g"), LoadColumn(5)]
        public float Weight_g { get; set; }


        [ColumnName("SIM"), LoadColumn(6)]
        public float SIM { get; set; }


        [ColumnName("display"), LoadColumn(7)]
        public float Display { get; set; }


        [ColumnName("OS"), LoadColumn(8)]
        public string OS { get; set; }


        [ColumnName("CPU"), LoadColumn(9)]
        public float CPU { get; set; }


        [ColumnName("memory_card"), LoadColumn(10)]
        public float Memory_card { get; set; }


        [ColumnName("internal_memory"), LoadColumn(11)]
        public float Internal_memory { get; set; }


        [ColumnName("RAM"), LoadColumn(12)]
        public float RAM { get; set; }


        [ColumnName("camera"), LoadColumn(13)]
        public float Camera { get; set; }


        [ColumnName("loud_speaker"), LoadColumn(14)]
        public float Loud_speaker { get; set; }


        [ColumnName("audio_jack"), LoadColumn(15)]
        public float Audio_jack { get; set; }


        [ColumnName("bluetooth"), LoadColumn(16)]
        public float Bluetooth { get; set; }


        [ColumnName("GPS"), LoadColumn(17)]
        public float GPS { get; set; }


        [ColumnName("NFC"), LoadColumn(18)]
        public float NFC { get; set; }


        [ColumnName("radio"), LoadColumn(19)]
        public float Radio { get; set; }


        [ColumnName("baterry"), LoadColumn(20)]
        public float Baterry { get; set; }


        [ColumnName("approx_price_EUR"), LoadColumn(21)]
        public float Approx_price_EUR { get; set; }


    }
}
